[build-system]
requires = ["poetry-core>=1.0.0", "Cython>=0.29.24", "numpy<1.23", "setuptools<65.6.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "g-invariance"
homepage = "https://github.com/geometric-intelligence/g-invariance"
version = "0.0.1"
description = "G-invariance"
authors = ["team@ucsb"]
readme = "README.md"
packages = [
    {include = "g_invariance"}
]
repository = "https://github.com/geometric-intelligence/g-invariance"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    #"D100",
    "G",
    #"CPY001"
]

[tool.ruff.lint.per-file-ignores]
"**/*_test.py" = ["D100"]

[tool.ruff.lint.isort]
known-first-party = ["atmocast", "atlas_client"]

[tool.ruff.format]
quote-style = "single"