# Misc and system settings
name: 'g-invariance'
dataset_dir: '/tmp/datasets/'
seed: 42
checkpoint_dir: "checkpoints/"
checkpoint_name_pattern: 'g-invariance-{epoch:03d}'
log_every_n_steps: 1
progress_bar: true

# Data
data_augmentation: 'so2'
augmentation_factor: 1
img_size: 16

# Training
batch_size: 128
gpu_count: 1
num_workers: 8
lr: 0.001
max_epochs: 30

# Model specs
model_name: 'GInvNet'
# model_name: 'VanillaNet'
N: 8
pooling: 'tc'
group: 'dihedral'
dataset_name: 'EMNIST'
n_filters: 20
fc_sizes: [64, 64, 64, 26]