# Misc and system settings
name: "g-invariance-test"
dataset_dir: "/tmp/datasets/"
seed: 42
checkpoint_dir: "checkpoints/"
checkpoint_name_pattern: "g-invariance-{epoch:03d}"
log_every_n_steps: 1
progress_bar: true

# Data
data_augmentation: "so2"
augmentation_factor: 2
img_size: 16

# Training
batch_size: 128
gpu_count: 1
num_workers: 8
lr: 0.0005
max_epochs: 15

# Model specs
model_name: "GInvNet" # ConvNet, VanillaNet
# dimension is currently hardcoded in BSP
N: 8
pooling: "avg"
group: "cyclic"
dataset_name: "MNIST"
dropout: 0.2
n_input_channels: 1
n_filters: 2
circle_crop: true
# first fc size is auto determined
# from target param count
target_params_count: 400000
fc_sizes: [64, 64, 10]
