name: 'mnist'
seed: 42
lr: 0.001
checkpoint_dir: "checkpoints/"
checkpoint_name_pattern: 'mnist-{epoch:03d}'
log_every_n_steps: 10
max_epochs: 5
warmup_epochs: 20
progress_bar: true

# Training
batch_size: 512
gpu_count: 1
workers: 10
transform: 'O2'
num_workers: 8
N: 8
pooling: 'bsp'
group_type: 'dihedral'
out_dim: 26
dataset_name: 'MNIST' # Any dataset from https://pytorch.org/vision/stable/datasets.html
continuous_group: 'O2'
augmentation_factor: 2
dataset_dir: '/tmp/datasets/'